'use client';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, BookOpen, CalendarDays, Check, CheckCircle2, Clock3, FileText, Leaf, Menu, Plus, Save, Settings, Target, Trash2, Upload, X, Play, Pause, RotateCcw } from 'lucide-react';
import { UserButton, useUser } from '@clerk/nextjs';

type Topic={id:string;name:string;done:boolean};
type Subject={id:string;name:string;topics:Topic[]};
type Task={id:string;title:string;subject:string;date:string;minutes:number;done:boolean};
type Note={id:string;title:string;body:string;updated:string};
type Test={id:string;title:string;subject:string;questions:number;score?:number;date:string};

const seedSubjects:Subject[]=[
 {id:'polity',name:'Polity',topics:['Constitutional Framework','Fundamental Rights','Parliament','Judiciary','Federalism','Local Government'].map((name,i)=>({id:'p'+i,name,done:i<4}))},
 {id:'history',name:'Modern History',topics:['Advent of Europeans','1857 Revolt','Socio-Religious Reform','National Movement','Gandhian Era'].map((name,i)=>({id:'h'+i,name,done:i<2}))},
 {id:'geo',name:'Geography',topics:['Geomorphology','Climatology','Indian Geography','Resources','Mapping'].map((name,i)=>({id:'g'+i,name,done:i<1}))},
 {id:'economy',name:'Economy',topics:['National Income','Inflation','Monetary Policy','Fiscal Policy','Banking'].map((name)=>({id:crypto.randomUUID(),name,done:false}))}
];
const seedTasks:Task[]=[{id:'t1',title:'Read — Fundamental Rights',subject:'Polity',date:new Date().toISOString().slice(0,10),minutes:50,done:true},{id:'t2',title:'Watch lecture — Monsoon System',subject:'Geography',date:new Date().toISOString().slice(0,10),minutes:60,done:false},{id:'t3',title:'Practice — Economy MCQs',subject:'Economy',date:new Date().toISOString().slice(0,10),minutes:40,done:false}];
const nav=[['Dashboard',BarChart3],['My Syllabus',BookOpen],['Planner',CalendarDays],['Study Sessions',Clock3],['Tests & Revision',Target],['Notes',FileText]] as const;
const uid=()=>crypto.randomUUID();

export default function App(){
 const {user}=useUser();
 const [tab,setTab]=useState('Dashboard'); const [subjects,setSubjects]=useState<Subject[]>([]); const [tasks,setTasks]=useState<Task[]>([]); const [notes,setNotes]=useState<Note[]>([]); const [tests,setTests]=useState<Test[]>([]); const [loaded,setLoaded]=useState(false); const [mobile,setMobile]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{const r=await fetch('/api/sync',{cache:'no-store'});if(!r.ok)throw new Error('load');const d=await r.json();if(active){setSubjects(d.subjects?.length?d.subjects:seedSubjects);setTasks(d.tasks||[]);setNotes(d.notes||[]);setTests(d.tests||[]);setLoaded(true)}}catch{if(active){setSubjects(seedSubjects);setTasks(seedTasks);setLoaded(true)}}})();return()=>{active=false}},[]);
 useEffect(()=>{if(!loaded)return;const timer=setTimeout(()=>{fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjects,tasks,notes,tests})}).catch(()=>{})},350);return()=>clearTimeout(timer)},[subjects,tasks,notes,tests,loaded]);
 const progress=useMemo(()=>{const all=subjects.flatMap(s=>s.topics);return all.length?Math.round(all.filter(t=>t.done).length/all.length*100):0},[subjects]);
 const toggleTask=(id:string)=>setTasks(v=>v.map(t=>t.id===id?{...t,done:!t.done}:t));
 return <div className="app">
  <aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="logo"><Leaf size={21}/></div><div><b>ExamPrep</b><span>Planner</span></div></div><nav>{nav.map(([x,I])=><button className={tab===x?'nav active':'nav'} onClick={()=>{setTab(x);setMobile(false)}} key={x}><I size={18}/>{x}</button>)}</nav><button className="nav bottom" onClick={()=>setTab('Settings')}><Settings size={18}/>Settings</button></aside>
  <section className="content"><header><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">GOOD MORNING, {user?.firstName || "ASPIRANT"}</p><h1>Study with clarity.</h1><p className="muted">Your preparation, organized without the noise.</p></div><UserButton appearance={{elements:{avatarBox:"avatar"}}}/></header>
   {tab==='Dashboard'&&<Dashboard subjects={subjects} tasks={tasks} progress={progress} setTab={setTab} toggleTask={toggleTask}/>} 
   {tab==='My Syllabus'&&<Syllabus subjects={subjects} setSubjects={setSubjects}/>} 
   {tab==='Planner'&&<Planner tasks={tasks} setTasks={setTasks} subjects={subjects} toggleTask={toggleTask}/>} 
   {tab==='Study Sessions'&&<Sessions/>}
   {tab==='Tests & Revision'&&<Tests tests={tests} setTests={setTests} subjects={subjects}/>} 
   {tab==='Notes'&&<Notes notes={notes} setNotes={setNotes}/>} 
   {tab==='Settings'&&<SettingsPage subjects={subjects} setSubjects={setSubjects} setTasks={setTasks} setNotes={setNotes} setTests={setTests}/>} 
  </section>
 </div>
}

function Dashboard({subjects,tasks,progress,setTab,toggleTask}:{subjects:Subject[];tasks:Task[];progress:number;setTab:(x:string)=>void;toggleTask:(x:string)=>void}){const done=subjects.reduce((a,s)=>a+s.topics.filter(t=>t.done).length,0);const total=subjects.reduce((a,s)=>a+s.topics.length,0);const week=tasks.reduce((a,t)=>a+t.minutes,0);return <>
 <div className="hero"><div><div className="pill"><Leaf size={14}/> Today’s focus</div><h2>Build momentum, one topic at a time.</h2><p>{tasks.filter(t=>!t.done).length} planned sessions · {Math.floor(week/60)}h {week%60}m study time</p><button className="primary" onClick={()=>setTab('Planner')}>View today’s plan →</button></div><div className="ring"><strong>{progress}%</strong><span>overall</span></div></div>
 <div className="grid3"><Stat icon={<CheckCircle2/>} value={`${done}`} label="Topics completed"/><Stat icon={<Clock3/>} value={`${(week/60).toFixed(1)}h`} label="Study planned"/><Stat icon={<Target/>} value={`${subjects.reduce((a,s)=>a+s.topics.filter(t=>!t.done).length,0)}`} label="Topics remaining"/></div>
 <div className="sectionHead"><div><h3>Syllabus progress</h3><p className="muted">Keep every subject moving.</p></div><button className="textBtn" onClick={()=>setTab('My Syllabus')}>View syllabus →</button></div>
 <div className="subjects">{subjects.map(s=><SubjectCard key={s.id} s={s}/>)}</div>
 <div className="sectionHead"><div><h3>Today</h3><p className="muted">A simple plan for a productive day.</p></div></div><div className="today">{tasks.slice(0,6).map(t=><TaskRow key={t.id} t={t} toggle={toggleTask}/>)}</div>
 </>}
function Stat({icon,value,label}:any){return <div className="stat"><div className="statIcon">{icon}</div><div><b>{value}</b><span>{label}</span></div></div>}
function SubjectCard({s}:{s:Subject}){const p=s.topics.length?Math.round(s.topics.filter(t=>t.done).length/s.topics.length*100):0;return <div className="subject"><div className="subjectTop"><div className="book"><BookOpen size={18}/></div><div><b>{s.name}</b><small>{s.topics.filter(t=>t.done).length} of {s.topics.length} topics</small></div><span>{p}%</span></div><div className="bar"><i style={{width:`${p}%`}}/></div></div>}
function TaskRow({t,toggle}:{t:Task;toggle:(id:string)=>void}){return <div className="task"><span className="time">{t.minutes} min</span><button className={t.done?'check checked':'check'} onClick={()=>toggle(t.id)}>{t.done&&<Check size={14}/>}</button><div><b className={t.done?'strike':''}>{t.title}</b><small>{t.subject}</small></div></div>}

function Syllabus({subjects,setSubjects}:{subjects:Subject[];setSubjects:React.Dispatch<React.SetStateAction<Subject[]>>}){const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Subject|null>(null);const [name,setName]=useState('');const [raw,setRaw]=useState('');const [fileName,setFileName]=useState('');
 const add=()=>{if(!name.trim())return;setSubjects(v=>[...v,{id:uid(),name:name.trim(),topics:raw.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>({id:uid(),name:x.replace(/^[-•*\d.)]+\s*/,''),done:false}))}]);setName('');setRaw('');setFileName('');setOpen(false)};
 const importFile=async(f:File)=>{setFileName(f.name); if(f.type==='text/plain'||f.name.toLowerCase().endsWith('.txt')||f.name.toLowerCase().endsWith('.md')||f.name.toLowerCase().endsWith('.csv')){setRaw(await f.text());return;} const fd=new FormData();fd.append('file',f);try{const r=await fetch('/api/parse-syllabus',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Parse failed');setRaw(d.text||'');}catch(e){alert(e instanceof Error?e.message:'Could not parse file');setRaw('');}};
 const saveEdit=(s:Subject)=>setSubjects(v=>v.map(x=>x.id===s.id?s:x));
 return <div><div className="pageTitle"><div><p className="eyebrow">YOUR CURRICULUM</p><h2>My Syllabus</h2><p className="muted">Type, paste or upload your own syllabus. Everything is editable.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/> Add subject</button></div>
 <div className="import"><div className="importIcon"><Upload/></div><div><h3>Import a syllabus</h3><p>TXT, Markdown, CSV, PDF and DOCX files are parsed into editable topics.</p></div><button className="secondary" onClick={()=>setOpen(true)}>Choose file</button></div>
 <div className="subjects big">{subjects.map(s=><div className="subject" key={s.id}><SubjectCard s={s}/><div className="topicList">{s.topics.map(t=><button key={t.id} className={t.done?'topic done':'topic'} onClick={()=>saveEdit({...s,topics:s.topics.map(q=>q.id===t.id?{...q,done:!q.done}:q)})}><span>{t.done?'✓':'○'}</span>{t.name}</button>)}</div><div className="cardActions"><button className="outline" onClick={()=>{setEditing(s);setName(s.name)}}>Edit</button><button className="danger" onClick={()=>setSubjects(v=>v.filter(x=>x.id!==s.id))}><Trash2 size={14}/></button></div></div>)}</div>
 {open&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setOpen(false)}><X/></button><div className="modalIcon"><BookOpen/></div><h2>Add a subject</h2><p className="muted">Create a subject and optionally paste one topic per line.</p><label>Subject name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Public Administration"/></label><label className="drop"><Upload size={20}/><span>{fileName||'Upload syllabus TXT, PDF or DOCX'}</span><input type="file" accept=".pdf,.docx,.doc,.txt" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label><label>Topics / syllabus<textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'Constitutional Framework\nFundamental Rights\nParliament\nJudiciary'}/></label><button className="primary full" onClick={add}>Create subject</button></div></div>}
 {editing&&<EditModal s={editing} close={()=>setEditing(null)} save={s=>{saveEdit(s);setEditing(null)}}/>}</div>}
function EditModal({s,close,save}:{s:Subject;close:()=>void;save:(s:Subject)=>void}){const [name,setName]=useState(s.name);const [topics,setTopics]=useState(s.topics);return <div className="overlay"><div className="modal wide"><button className="close" onClick={close}><X/></button><h2>Edit syllabus</h2><label>Subject name<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="editTopics">{topics.map((t,i)=><div className="editRow" key={t.id}><input value={t.name} onChange={e=>setTopics(v=>v.map((q,j)=>j===i?{...q,name:e.target.value}:q))}/><button className={t.done?'check checked':'check'} onClick={()=>setTopics(v=>v.map(q=>q.id===t.id?{...q,done:!q.done}:q))}>{t.done&&<Check size={14}/>}</button><button className="danger" onClick={()=>setTopics(v=>v.filter(q=>q.id!==t.id))}><Trash2 size={14}/></button></div>)}</div><button className="secondary" onClick={()=>setTopics(v=>[...v,{id:uid(),name:'New topic',done:false}])}>+ Add topic</button><button className="primary full" onClick={()=>save({...s,name,topics})}><Save size={15}/> Save changes</button></div></div>}

function Planner({tasks,setTasks,subjects,toggleTask}:{tasks:Task[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;subjects:Subject[];toggleTask:(x:string)=>void}){const [title,setTitle]=useState('');const [subject,setSubject]=useState(subjects[0]?.name||'');const [minutes,setMinutes]=useState(45);const [date,setDate]=useState(new Date().toISOString().slice(0,10));const add=()=>{if(!title.trim())return;setTasks(v=>[...v,{id:uid(),title,subject,date,minutes:Number(minutes),done:false}]);setTitle('')};return <div><div className="pageTitle"><div><p className="eyebrow">PLAN YOUR DAY</p><h2>Planner</h2><p className="muted">Turn your syllabus into realistic study blocks.</p></div></div><div className="plannerGrid"><div className="panel"><h3>Add a study block</h3><label>Task<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Revise Fundamental Rights"/></label><div className="two"><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s.id}>{s.name}</option>)}</select></label><label>Minutes<input type="number" min="5" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></div><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary full" onClick={add}><Plus size={15}/> Add to plan</button></div><div><h3 className="listTitle">Study plan</h3><div className="today">{tasks.map(t=><div className="task" key={t.id}><span className="time">{t.date}</span><button className={t.done?'check checked':'check'} onClick={()=>toggleTask(t.id)}>{t.done&&<Check size={14}/>}</button><div><b className={t.done?'strike':''}>{t.title}</b><small>{t.subject} · {t.minutes} min</small></div><button className="danger" onClick={()=>setTasks(v=>v.filter(x=>x.id!==t.id))}><Trash2 size={14}/></button></div>)}</div></div></div></div>}

function Sessions(){const [seconds,setSeconds]=useState(25*60);const [running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const i=setInterval(()=>setSeconds(s=>s>0?s-1:0),1000);return()=>clearInterval(i)},[running]);const m=Math.floor(seconds/60).toString().padStart(2,'0'),s=(seconds%60).toString().padStart(2,'0');return <div><div className="pageTitle"><div><p className="eyebrow">FOCUS MODE</p><h2>Study Sessions</h2><p className="muted">A simple Pomodoro timer for distraction-free work.</p></div></div><div className="timerCard"><div className="timer">{m}:{s}</div><div className="timerControls"><button className="primary" onClick={()=>setRunning(!running)}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Pause':'Start focus'}</button><button className="secondary" onClick={()=>{setRunning(false);setSeconds(25*60)}}><RotateCcw size={16}/> Reset</button></div><div className="presets"><button onClick={()=>{setRunning(false);setSeconds(25*60)}}>25 min</button><button onClick={()=>{setRunning(false);setSeconds(50*60)}}>50 min</button><button onClick={()=>{setRunning(false);setSeconds(90*60)}}>90 min</button></div></div></div>}

function Tests({tests,setTests,subjects}:{tests:Test[];setTests:React.Dispatch<React.SetStateAction<Test[]>>;subjects:Subject[]}){const [title,setTitle]=useState('');const [subject,setSubject]=useState(subjects[0]?.name||'');const [q,setQ]=useState(20);const add=()=>{if(!title)return;setTests(v=>[{id:uid(),title,subject,questions:q,date:new Date().toISOString().slice(0,10)},...v]);setTitle('')};return <div><div className="pageTitle"><div><p className="eyebrow">PRACTICE & RECALL</p><h2>Tests & Revision</h2><p className="muted">Log mock tests and keep revision visible.</p></div></div><div className="plannerGrid"><div className="panel"><h3>Log a test</h3><label>Test name<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="UPSC Prelims Mock 01"/></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s.id}>{s.name}</option>)}</select></label><label>Questions<input type="number" value={q} onChange={e=>setQ(Number(e.target.value))}/></label><button className="primary full" onClick={add}>Add test</button></div><div><h3 className="listTitle">Your tests</h3>{tests.length===0?<Empty text="No tests logged yet."/>:<div className="today">{tests.map(t=><div className="task" key={t.id}><div className="book"><Target size={17}/></div><div><b>{t.title}</b><small>{t.subject} · {t.questions} questions · {t.date}</small></div><button className="danger" onClick={()=>setTests(v=>v.filter(x=>x.id!==t.id))}><Trash2 size={14}/></button></div>)}</div>}</div></div></div>}

function Notes({notes,setNotes}:{notes:Note[];setNotes:React.Dispatch<React.SetStateAction<Note[]>>}){const [selected,setSelected]=useState<Note|null>(notes[0]||null);const create=()=>{const n={id:uid(),title:'Untitled note',body:'',updated:new Date().toISOString()};setNotes(v=>[n,...v]);setSelected(n)};const update=(n:Note)=>{setSelected(n);setNotes(v=>v.map(x=>x.id===n.id?n:x))};return <div><div className="pageTitle"><div><p className="eyebrow">YOUR KNOWLEDGE BASE</p><h2>Notes</h2><p className="muted">Keep concise notes attached to your preparation.</p></div><button className="primary" onClick={create}><Plus size={16}/> New note</button></div>{notes.length===0?<Empty text="Create your first note."/>:<div className="notes"><div className="noteList">{notes.map(n=><button className={selected?.id===n.id?'noteItem selected':'noteItem'} key={n.id} onClick={()=>setSelected(n)}><b>{n.title||'Untitled'}</b><small>{n.body.slice(0,45)||'Empty note'}</small></button>)}</div>{selected&&<div className="noteEditor"><input className="noteTitle" value={selected.title} onChange={e=>update({...selected,title:e.target.value,updated:new Date().toISOString()})}/><textarea value={selected.body} onChange={e=>update({...selected,body:e.target.value,updated:new Date().toISOString()})} placeholder="Write your note…"/><button className="danger" onClick={()=>{setNotes(v=>v.filter(n=>n.id!==selected.id));setSelected(notes.find(n=>n.id!==selected.id)||null)}}><Trash2 size={14}/> Delete note</button></div>}</div>}</div>}
function Empty({text}:{text:string}){return <div className="empty"><FileText size={28}/><b>{text}</b><span>Everything you add is saved securely to your account.</span></div>}
function SettingsPage({subjects,setSubjects,setTasks,setNotes,setTests}:{subjects:Subject[];setSubjects:React.Dispatch<React.SetStateAction<Subject[]>>;setTasks:React.Dispatch<React.SetStateAction<Task[]>>;setNotes:React.Dispatch<React.SetStateAction<Note[]>>;setTests:React.Dispatch<React.SetStateAction<Test[]>>}){const reset=async()=>{if(confirm('Reset all your ExamPrep Planner data?')){setSubjects(seedSubjects);setTasks(seedTasks);setNotes([]);setTests([]);await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjects:seedSubjects,tasks:seedTasks,notes:[],tests:[]})});}};return <div><div className="pageTitle"><div><p className="eyebrow">PREFERENCES</p><h2>Settings</h2><p className="muted">Your account is secured by Clerk and your planner data is stored in Vercel-friendly Postgres.</p></div></div><div className="panel settings"><div className="setting"><div><b>Data storage</b><span>Your syllabus, planner, notes and tests are stored locally in your browser.</span></div><span className="status">Cloud</span></div><div className="setting"><div><b>Subjects</b><span>{subjects.length} subjects in your curriculum.</span></div><span className="status">Active</span></div><div className="setting"><div><b>Reset demo data</b><span>Restore the starter syllabus and clear local changes.</span></div><button className="danger" onClick={reset}>Reset</button></div></div></div>}
